name: Publish
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/npm-package-publish.yml
    with:
      environment: Production
